### ISSUE TITLE
Airbags Don't Get Deleted

### ISSUE THREAD

**Issue by ColinTheBossReal** [Owen-M/obAirbags#1]
When deleting a vehicle the airbags do to get deleted and just stay floating in the air. Also, there is no way to remove the airbags once they are deployed.

![image](https://user-images.githubusercontent.com/57803845/235277012-dcb22b5f-74b0-4808-a3b7-e2231e5ef80a.png)

**Comment by Owen-M** [comment]
Did you try /removeAirbags in the vehicle when the Airbags were deployed? This command has been tested countless times and works without issues for our team. As for the airbags remaining floating, we will investigate this but haven't had the issue ourselves.

**Comment by ColinTheBossReal** [comment]
I tried the Remove Airbags command. It did not work.
